name: Build

on:
  push:
    branches: [ handson ]
  pull_request:
    branches: [ handson ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    # Java (今回アプリケーションを作る言語) を使えるようにする
    - uses: actions/checkout@v2
    - name: Set up JDK 11
      uses: actions/setup-java@v2
      with:
        java-version: '11'
        distribution: 'adopt'

    # JFrog　CLIを使えるようにする
    - name: Set up JFrog CLI
      uses: jfrog/setup-jfrog-cli@v2

    # TODO: アプリケーションをテスト・ビルドし、Artifactoryにプッシュする
    - name: Build and publish the Gradle application

    # TODO: 脆弱性のスキャンを行う