name: Build

on:
  push:
    branches: [ handson ]
  pull_request:
    branches: [ handson ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    # Java (今回アプリケーションを作る言語) を使えるようにする
    - uses: actions/checkout@v2
    - name: Set up JDK 11
      uses: actions/setup-java@v2
      with:
        java-version: '11'
        distribution: 'adopt'

    # JFrog　CLIを使えるようにする
    - name: Set up JFrog CLI
      uses: jfrog/setup-jfrog-cli@v2

    # TODO: アプリケーションをテスト・ビルドし、Artifactoryにプッシュする
    - name: Build and publish the Gradle application
      run: |
        jfrog c add my-jfrog-server --url=https://${{ secrets.JFROG_URL }}/ --user=${{ secrets.JFROG_USER }} --password=${{ secrets.JFROG_ENCRYPTED_PASSWORD }}
        jfrog rt gradle-config --server-id-resolve=my-jfrog-server --server-id-deploy=my-jfrog-server --repo-resolve=handson-gradle --repo-deploy=handson-gradle --use-wrapper=true
        jfrog rt gradle clean test artifactoryPublish -b build.gradle --build-name=handson-build --build-number=${{ env.JFROG_CLI_BUILD_NUMBER }}
        jfrog rt bce handson-build ${{ env.JFROG_CLI_BUILD_NUMBER }}
        jfrog rt bp handson-build ${{ env.JFROG_CLI_BUILD_NUMBER }}

    # TODO: 脆弱性のスキャンを行う
