name: Promote

on:
  workflow_dispatch

jobs:

  promote:

    runs-on: ubuntu-latest

    steps:
      - uses: jfrog/setup-jfrog-cli@v2
      # 次の環境 (ここではステージング) のリポジトリにアーティファクトをプロモートする
      - name: Promote artifacts
        run: |
          jfrog c add my-jfrog-server --url=https://${{ secrets.JFROG_URL }}/ --user=${{ secrets.JFROG_USER }} --password=${{ secrets.JFROG_ENCRYPTED_PASSWORD }}
          passedBuildNumber=`jfrog rt s "*.jar" --server-id=my-jfrog-server --props="qa=ok" | jq -r '.[].props."build.number"[]'`
          jfrog rt bpr handson-build $passedBuildNumber handson-gradle-staging --server-id=my-jfrog-server