name: Release

on:
  workflow_dispatch

jobs:

  promote:

    runs-on: ubuntu-latest

    steps:
      - uses: jfrog/setup-jfrog-cli@v2
      - name: Push artifacts to JFrog
        run: |
          jfrog c add my-jfrog-server --url=https://${{ secrets.JFROG_URL }}/ --user=${{ secrets.JFROG_USER }} --password=${{ secrets.ENCRYPTED_PASSWORD }}
          passedBuildNumber=`jfrog rt s "*.jar" --server-id=my-jfrog-server --props="qa=ok" | jq -r '.[].props."build.number"[]'`
          jfrog rt bpr handson-build $passedBuildNumber staging --server-id=my-jfrog-server